Iter5
MilkaDurilka/linkshrink pull request #5
Opened 2024-12-01 20:26 UTC by MilkaDurilka

Перменные окружения: SERVER_ADDRESS и BASE_URL.

Нужна помощь с golanci-lint. Локально файл report.json пустой и пре-комит не срабатывает. Автотесты падают, но как прочитать ошибки непонятно. Не хватает указания на строку в файле. Можно ли настроить подсветку этих ошибок в коде в VS Code?

2024-12-04 11:47 UTC, s-shpak requested changes
Не резолвь, пожалуйста, мои комментарии: мне нужно видеть, что именно мы обсуждали в повторном ревью. Если тебе хочется как-то трекать исправленные замечания, выставляй, например, реакции к комментариям.

По поводу линтера:
для получения более удобного отчета достаточно запустить линтер локально при помощи `make golangci-lint-run` из корня проекта (ты работаешь на линуксе или маке?). Это сгенерирует отчет в `golangci-lint/report.json` в котором указано где произошла та или иная ошибка:

![image](https://github.com/user-attachments/assets/3e544701-ea30-4070-9b90-ae2953428d84)

2024-12-04 11:47 UTC, s-shpak commented on internal/app/app.go
> +				log.Fatalf("Error initializing config: %v", err)
`log.Fatal` завершает процесс с ненулевым кодом завершения (что указывает на то, что процесс завершился с ошибкой). Не стоит делать это из глубины кода: лучше прокинуть ошибку наверх, т.к. возможно наверху мы сможем ее обработать. Если подходящего обработчика нет, то ошибка должна дойти до точки входа, спровоцировать graceful shutdown приложения и, после, завершение процесса.

2024-12-04 11:47 UTC, s-shpak commented on internal/app/app.go
> +		cfg, err := config.InitConfig()
В каком IDE ты работаешь ? В VSCode и GoLand должны по умолчанию применяяться `go fmt` и `goimports`: по идее, при сохранении файла, код должен выравниваться автоматически. Может быть надо как-то донастроить их ?

2024-12-04 11:47 UTC, s-shpak commented on internal/config/config.go
> +		addressEnv := os.Getenv("SERVER_ADDRESS")
Вместо `Getenv` лучше использовать `LookupEnv` (https://pkg.go.dev/os#LookupEnv) для того чтобы отличать пустую переменную окружения от необъявленной

2024-12-04 11:47 UTC, s-shpak commented on internal/controller/controller.go
> +			http.Error(w, "Error shortening URL", http.StatusInternalServerError)
Нештатные ошибки (5**) нужно логировать. А вот отправлять пользователю детали о ней (что именно пошло не так и где) нельзя, т.к. это угроза безопасности приложения.

2024-12-04 11:47 UTC, s-shpak commented on internal/controller/controller.go
> +    id := vars["id"] // Извлекаем ID из переменных маршрута
Здесь можно проверить, что ключ в мапе существует

2024-12-04 11:47 UTC, s-shpak commented on internal/repository/repository.go
> +    mu    sync.RWMutex // Мьютекс для обеспечения потокобезопасности
Правильно хранить указатель на мьютекс, а не сам мьютекс -- мьютекс нельзя копировать после инициализации. Почему это так мы, возмжно, разберем во второй части курса, пока это правило лучше просто запомнить

2024-12-04 11:47 UTC, s-shpak commented on internal/service/service.go
> +        return "", ErrInvalidURL
В ошибки лучше добавлять контекст: например, текст, объясняющий, что именно пошло не так и где

2024-12-04 11:47 UTC, s-shpak commented on internal/repository/repository.go
> +func (r *URLRepository) Save(id, originalURL string) error {
Т.к. сокращенный URL генерируется случайно, существует риск коллизии. Подумай, что можно сделать в этом случае

2024-12-07 18:52 UTC, MilkaDurilka commented on internal/repository/repository.go
> +func (r *URLRepository) Save(id, originalURL string) error {
перешла на uuid v4, чтобы минимизировать вероятность коллизий

2024-12-07 18:52 UTC, MilkaDurilka commented on internal/app/app.go
> +		cfg, err := config.InitConfig()
работаю в VSCode

2024-12-09 09:27 UTC, s-shpak commented on internal/app/app.go
> +		cfg, err := config.InitConfig()
Я надеюсь, что проблма решена, если нет -- напиши в пачку.

2024-12-09 09:29 UTC, s-shpak commented on internal/config/config.go
> +	envVar, exists := os.LookupEnv(envVarKey)
Если функция в Go возвращает вторую переменную булевого типа, которая указывает на корректность выполнения операции и т.п., ее принято называть `ok`.

2024-12-09 09:29 UTC, s-shpak commented on internal/repository/repository.go
> +func (r *URLRepository) Save(id, originalURL string) error {
`uuid` может приветси к тому, что "сокращенная" ссылка станет длинее оригинальной. Лучше генерируй значения случайно, установив какой-то лимит на длину URL. Если случается коллизия, то URL можно перегенерировать. Если таких ошибок случилось более `n`, то можно вернуть клиенту Internal Server Error

2024-12-09 09:30 UTC, s-shpak requested changes

2024-12-09 09:30 UTC, s-shpak commented on internal/repository/repository.go
> +	mu    *sync.RWMutex     // Мьютекс для обеспечения потокобезопасности
Круто, что ты знаешь о существовании `RWMutex`, но в в данном случае лучше использовать обычный, т.к. с `RWMutex` твое приложение, скорее всего, будет работать медленее. `RWMutex` можно исползовать если количество записей на порядки превышает количество чтений, и его воздействие на быстродействие приложения стоит проверять при помощи бенчмаркинга

2024-12-09 19:47 UTC, MilkaDurilka commented on internal/repository/repository.go
> +	mu    *sync.RWMutex     // Мьютекс для обеспечения потокобезопасности
Mutex: Лучше подходит для случаев, когда доступ к ресурсу осуществляется в основном для записи, так как он проще и требует меньше накладных расходов.
RWMutex: Более эффективен в сценариях, где чтение происходит гораздо чаще, чем запись. Это позволяет улучшить производительность, позволяя нескольким горутинам одновременно читать данные.

по идее запросов на чтение должно быть больше. Но соглашусь, что до проведения анализа нагрузки оптимизация избыточна.

2024-12-09 23:01 UTC, s-shpak requested changes

2024-12-09 23:01 UTC, s-shpak commented on internal/repository/repository.go
> +		id = utils.NewIDGenerator().GenerateID()
Кажется, что генерация короткой ссылки -- ответственность не хранилища, а слоя бизнес-логики. Перенси этот функционал лучше в `service.go`

2024-12-10 05:25 UTC, MilkaDurilka commented on internal/repository/repository.go
> +		id = utils.NewIDGenerator().GenerateID()
генерация короткой ссылки и происходит в service.go https://github.com/MilkaDurilka/linkshrink/blob/iter5/internal/service/service.go#L43

а в хранилище происходит генерация id, с которым сохраняются данные. В моей концепции id относится к repository, но так же участвует в формировании ссылки, но об этом знает только service.

Пожалуйста, объясни, почему стоит перенести  генерацию id. Спасибо за помощь!

2024-12-10 12:46 UTC, s-shpak commented on internal/repository/repository.go
> +		id = utils.NewIDGenerator().GenerateID()
Да. конечно.

С моей т.з. формат короткой ссылки зависит от бизнес-логики приложения. Например, как выбрать длину `id` ? Зависит от ожидаемого количества сокращенных ссылок. Как выбрать алфавит `id` ? Зависит от интерфейса взаимодействия с клиентом (в веб-браузере, например, это будет кодировка совместимая с URL). Следует ли генерировать id случайно или получать их при помощи хеширования ? Зависит от выбранной стратегии разрешения коллизий и обработки URL, которые раннее уже были сокращены.

Кажется, что все это -- ответственность слоя бизнес-логики, а не хранилища. WDYT?

Чтобы быстрее получать ответы, можно продолжить диалог в пачке.

2024-12-10 12:47 UTC, s-shpak requested changes
См. комментарий

2024-12-10 18:57 UTC, MilkaDurilka commented on internal/repository/repository.go
> +		id = utils.NewIDGenerator().GenerateID()
перенесла в service.go

2024-12-10 20:07 UTC, s-shpak requested changes

2024-12-10 20:07 UTC, s-shpak commented on internal/service/service.go
> +		log.Printf("Number of attempts exceeded: %s", originalURL)
Ошибки стоит (как правило) логировать в момент, когда они обрабатываются: т.е. когда ошибка возвращена на тот слой, где она может быть обработана, а не прокинута выше.

2024-12-10 20:07 UTC, s-shpak commented on internal/service/service.go
> +		return "", ErrInternalServer
В ошибку можно добавить контекст, чтобы залогировать выше.

```suggestion
		return "",  fmt.Errorf("%w: number of attempts exceeded: %s", ErrInternalServer, originalURL)
```

2024-12-10 20:07 UTC, s-shpak commented on internal/service/service.go
> +	if err := s.repo.Save(id, originalURL); err != nil {
Что если проверка завершилась успешно, но до того, как ты добавил новую коротку ссылку в хранилище, другая горутина добавит ее же (случайно сгенерирует такое же значение)? Подумай, как это исправить

2024-12-10 21:03 UTC, MilkaDurilka commented on internal/service/service.go
> +	if err := s.repo.Save(id, originalURL); err != nil {
спасибо! Убрала лишний find и сразу сохраняю. В метода save добавила проверку на занятость id.

2024-12-10 21:03 UTC, MilkaDurilka commented on internal/service/service.go
> +		log.Printf("Number of attempts exceeded: %s", originalURL)
Убрала лишние логи

2024-12-11 09:38 UTC, s-shpak approved these changes

2024-12-23 13:52 UTC, merged