Iter9
MilkaDurilka/linkshrink pull request #9
Opened 2024-12-24 03:31 UTC by MilkaDurilka

все сокращённые URL сохраняются на диск в виде файла. При перезапуске сервера все URL  восстановливаются

2024-12-24 19:09 UTC, s-shpak requested changes

2024-12-24 19:09 UTC, s-shpak commented on internal/controller/controller.go
>  		http.Error(w, "Internal server error", http.StatusInternalServerError)
Нештатные ошибки надо логировать

2024-12-24 19:09 UTC, s-shpak commented on internal/controller/controller.go
> +		log.Println("Error shortening URL: %w", err)
```suggestion
		log.Printf("Error shortening URL: %v", err)
```

2024-12-24 19:09 UTC, s-shpak commented on internal/controller/controller.go
> +		http.Error(w, "Unable to encode response", http.StatusInternalServerError)
Если ты отправляешь клиенту 500, то не стоит отдавать ему информациб о том, что именно пошло не так -- это небезопасно

2024-12-24 19:09 UTC, s-shpak commented on internal/handlers/handlers.go
> +	logger, err := zap.NewProduction()
Я бы рекомендовал создавать один корневой логгер где-то в `main`, а далее инджектить дочерние логгеры в те компоненты, которые их используют. В случае логгеров мы также придерживаемся принципов DI.

Кроме того в дочерние логгеры можно добавлять дополнительный контекст: например, имя компонента, который логгер использует. Для этого можно использовать это: https://pkg.go.dev/go.uber.org/zap#Logger.With

2024-12-24 19:09 UTC, s-shpak commented on internal/middleware/middleware.go
> +		// gzipResponseMiddleware, // не могу понять почему с этой мидлварой не проходили тесты, а когда закомментила - прошли
Я попробую посмотреть, что именно идет не так

2024-12-24 19:09 UTC, s-shpak commented on internal/middleware/middleware.go
> +				http.Error(w, "Failed to read body", http.StatusBadRequest)
Кажется, что даже это дает клиенту слишком много информации о том, как именно работает сервис под капотом. Я бы просто отправлял текст ошибки полученный при помощи https://pkg.go.dev/net/http#StatusText

2024-12-24 19:09 UTC, s-shpak commented on internal/middleware/middleware.go
> +			// gzipWriter.Close()
deadcode

2024-12-24 19:09 UTC, s-shpak commented on internal/repository/repository.go
> +	filePath string
В этом спринте мы добавляем обособленную часть функционала к хранилищу: запись в файл. То есть новый тип хранилища полностью повторяет функционал MemoryStore и расширяет его. Но мы оставляем возможность запустить сервис без записи в файл. Потому кажется логичным не изменять существующую структуру, и не дуплицировать функционал, а написать обертку над MemoryStore.

Для этого можно использовать композицию и встроить MemoryStore в новую структуру FileStore. При вызове сохранения, например, новая структура будет вызывать вначале добавление новой записи в память (через встроенный объект), а потом сохранение в файл.

В этом случае убедись, что ты выполняешь инициализацию нужного типа при старте сервиса (можно использовать паттерн Factory, как разбирали на первом вебинаре).

2024-12-24 19:09 UTC, s-shpak commented on internal/repository/repository.go
> +	// r.mu.Lock()
deadcode

2024-12-24 19:09 UTC, s-shpak commented on internal/repository/repository.go
> +	LoadFromFile() error
Я не думаю, что есть смысл изменять интерфейс хранилища: то, что оно использует файл для сохранения и восстановления данных, внешнему клиенту (слою бизнес-логики) должно быть безразлично

2024-12-24 19:09 UTC, s-shpak commented on internal/service/service_test.go
> +// Реализация метода LoadFromFile (добавьте свою логику здесь).
Вы добавили свою логику здесь ? :)

2025-01-05 18:40 UTC, MilkaDurilka commented on internal/controller/controller.go
>  		http.Error(w, "Internal server error", http.StatusInternalServerError)
done

2025-01-05 18:40 UTC, MilkaDurilka commented on internal/controller/controller.go
> +		log.Println("Error shortening URL: %w", err)
done

2025-01-05 18:40 UTC, MilkaDurilka commented on internal/controller/controller.go
> +		http.Error(w, "Unable to encode response", http.StatusInternalServerError)
done

2025-01-05 18:40 UTC, MilkaDurilka commented on internal/handlers/handlers.go
> +	logger, err := zap.NewProduction()
done

2025-01-05 18:40 UTC, MilkaDurilka commented on internal/middleware/middleware.go
> +			// gzipWriter.Close()
done

2025-01-05 18:41 UTC, MilkaDurilka commented on internal/repository/repository.go
> +	filePath string
done

2025-01-05 18:41 UTC, MilkaDurilka commented on internal/repository/repository.go
> +	// r.mu.Lock()
done

2025-01-05 18:41 UTC, MilkaDurilka commented on internal/repository/repository.go
> +	LoadFromFile() error
done

2025-01-05 18:41 UTC, MilkaDurilka commented on internal/service/service_test.go
> +// Реализация метода LoadFromFile (добавьте свою логику здесь).
да :) коммент убрала. Разве тут чего-то не хватает?

2025-01-06 09:48 UTC, s-shpak commented on internal/service/service_test.go
> +// Реализация метода LoadFromFile (добавьте свою логику здесь).
Нет, это просто сатрый комментарий, думаю -- лучше его убрать

2025-01-07 10:37 UTC, s-shpak approved these changes

2025-01-11 21:35 UTC, merged